
spring:
  profiles:
    active: development
  application:
    name: inventory-api
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: inventory
    out-of-order: true
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    hibernate:
      ddl-auto: none



---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
    url: jdbc:postgresql://localhost:5432/postgres

server:
  port: 5001

